import type { portfolioPhotos } from "@/types/portfolio";
import { v4 as uuidv4 } from "uuid";

export const PHOTOS: portfolioPhotos[] = [
  {
    id: uuidv4(),
    image: "",
    category: "children's parties",
    layout: "",
  },
  {
    image: "",
    id: uuidv4(),
    category: "children's parties",
    layout: "",
  },
  {
    image: "",
    id: uuidv4(),
    category: "children's parties",
    layout: "",
  },
  {
    image: "",
    id: uuidv4(),
    category: "children's parties",
    layout: "",
  },
  {
    image: "",
    id: uuidv4(),
    category: "children's parties",
    layout: "",
  },
  {
    id: uuidv4(),
    image: "",
    category: "children's parties",
    layout: "",
  },
  {
    image: "",
    id: uuidv4(),
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "birthdays",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "graduations",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "conferences",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    image: "",
    layout: "",
    category: "baptisms",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
  {
    id: uuidv4(),
    layout: "",
    image: "",
    category: "weddings",
  },
];
